// mapeo de nodos del nuevo sistema de rutas basado en grafo de conexiones
// cada nodo representa un lugar (salón, pasillo, oficina, escalera, etc)
// los nodos se conectan directamente entre sí a través del array 'conexiones'

// tipos para el sistema de nodos
export interface MapNode {
  id: string // identificador único: número de salón, ID de oficina, o nombre de pasillo
  piso: 'Piso1' | 'Piso2' // en qué piso está el nodo
  x: number // coordenada X en píxeles del SVG
  y: number // coordenada Y en píxeles del SVG
  nombres?: string[] // nombres alternativos para buscar (ej: "Sala de juicios orales", "salón 106")
  tipo: 'salon' | 'pasillo' | 'oficina' | 'escalera' | 'entrada' | 'baño_m' | 'baño_h' | 'baño' | 'edificio' | 'elevador'
  conexiones: string[] // array de IDs de nodos conectados (vecinos directos)
}

export interface MapGraph {
  [nodeId: string]: MapNode
}

// definición completa de todos los nodos del campus
// estructura importada y convertida del archivo map.js de nuevarutamapa
export const nodos: MapGraph = {
  // ==== EDIFICIO 6 - PISO 1 ====
  ent_principal: {
    id: '100001',
    piso: 'Piso1',
    x: 1225,
    y: 30,
    nombres: ['Entrada Principal', 'Acceso'],
    tipo: 'entrada',
    conexiones: ['pas_1'],
  },
  pas_1: {
    id: 'pas_1',
    piso: 'Piso1',
    x: 1225,
    y: 260,
    tipo: 'pasillo',
    conexiones: ['ent_principal', 'ofi_1', 'sal_605', 'pas_2'],
  },
  ofi_1: {
    id: '60001',
    piso: 'Piso1',
    x: 1100,
    y: 260,
    nombres: ['Servicios escolares', 'caja', 'promocion'],
    tipo: 'oficina',
    conexiones: ['pas_1', 'pas_3'],
  },
  sal_605: {
    id: '605',
    piso: 'Piso1',
    x: 1315,
    y: 260,
    nombres: ['Salón 605'],
    tipo: 'salon',
    conexiones: ['pas_1', 'pas_63'],
  },
  pas_63: {
    id: 'pas_63',
    piso: 'Piso1',
    x: 1315,
    y: 300,
    tipo: 'pasillo',
    conexiones: ['sal_605', 'pas_2', 'sal_604'],
  },
  pas_2: {
    id: 'pas_2',
    piso: 'Piso1',
    x: 1225,
    y: 300,
    tipo: 'pasillo',
    conexiones: ['pas_1', 'pas_3', 'sal_604', 'pas_63', 'pas_central1'],
  },
  pas_3: {
    id: 'pas_3',
    piso: 'Piso1',
    x: 1110,
    y: 300,
    tipo: 'pasillo',
    conexiones: ['pas_2', 'esc_central', 'ofi_1'],
  },
  sal_604: {
    id: '604',
    piso: 'Piso1',
    x: 1420,
    y: 300,
    nombres: ['Salón 604'],
    tipo: 'salon',
    conexiones: ['pas_2', 'sal_603', 'pas_63'],
  },
  sal_603: {
    id: '603',
    piso: 'Piso1',
    x: 1500,
    y: 300,
    nombres: ['Salón 603'],
    tipo: 'salon',
    conexiones: ['sal_604', 'sal_602'],
  },
  sal_602: {
    id: '602',
    piso: 'Piso1',
    x: 1590,
    y: 300,
    nombres: ['Salón 602'],
    tipo: 'salon',
    conexiones: ['sal_603', 'ofi_2'],
  },
  ofi_2: {
    id: '60002',
    piso: 'Piso1',
    x: 1800,
    y: 300,
    nombres: ['DTI'],
    tipo: 'oficina',
    conexiones: ['sal_602', 'pas_4'],
  },
  pas_4: {
    id: 'pas_4',
    piso: 'Piso1',
    x: 1860,
    y: 300,
    tipo: 'pasillo',
    conexiones: ['ofi_2', 'esc_ed6', 'pas_est1', 'baño_m1'],
  },
  pas_est1: {
    id: 'pas_est1',
    piso: 'Piso1',
    x: 1975,
    y: 355,
    tipo: 'pasillo',
    conexiones: ['pas_4', 'baño_m1', 'pas_est2'],
  },
  baño_m1: {
    id: 'baño_m1',
    piso: 'Piso1',
    x: 1920,
    y: 300,
    tipo: 'baño_m',
    conexiones: ['pas_4', 'pas_est1'],
  },

  // ==== ESCALERAS PISO 1 ====
  esc_central: {
    id: 'esc_central',
    piso: 'Piso1',
    x: 1110,
    y: 320,
    tipo: 'escalera',
    conexiones: ['pas_3', 'p2_esc_central'],
  },
  esc_ed6: {
    id: 'esc_ed6',
    piso: 'Piso1',
    x: 1860,
    y: 320,
    tipo: 'escalera',
    conexiones: ['pas_4', 'p2_esc_ed6'],
  },
  esc_ed1centr: {
    id: 'esc_ed1centr',
    piso: 'Piso1',
    x: 1150,
    y: 600,
    tipo: 'escalera',
    conexiones: ['pas_11', 'p2_esc_ed1centr'],
  },
  esc_ed1ed5: {
    id: 'esc_ed1ed5',
    piso: 'Piso1',
    x: 290,
    y: 600,
    tipo: 'escalera',
    conexiones: ['pas_ed1ed5', 'p2_esc_ed1ed5'],
  },
  esc_ed2centr: {
    id: 'esc_ed2centr',
    piso: 'Piso1',
    x: 1150,
    y: 870,
    tipo: 'escalera',
    conexiones: ['pas_21', 'p2_esc_ed2centr'],
  },
  esc_ed3: {
    id: 'esc_ed3',
    piso: 'Piso1',
    x: 1150,
    y: 1110,
    tipo: 'escalera',
    conexiones: ['pas_31', 'p2_esc_ed3'],
  },
  ele_gastro1: {
    id: 'ele_gastro1',
    piso: 'Piso1',
    x: 560,
    y: 1190,
    tipo: 'escalera',
    conexiones: ['pas_gastro2', 'p2_ele_gastro1'],
  },
  esc_ed4: {
    id: 'esc_ed4',
    piso: 'Piso1',
    x: 295,
    y: 1360,
    tipo: 'escalera',
    conexiones: ['pas_42', 'p2_esc_ed4'],
  },
  ele500: {
    id: 'ele500',
    piso: 'Piso1',
    x: 200,
    y: 550,
    tipo: 'elevador',
    conexiones: ['pas_51', 'p2_ele500'],
  },
  esc_lab4: {
    id: 'esc_lab4',
    piso: 'Piso1',
    x: 580,
    y: 1570,
    tipo: 'escalera',
    conexiones: ['pas_lab42', 'pas_lab44', 'p2_esc_lab4'],
  },

  // ==== EDIFICIO 1 - PISO 1 ====
  pas_central1: {
    id: 'pas_central1',
    piso: 'Piso1',
    x: 1225,
    y: 540,
    tipo: 'pasillo',
    conexiones: ['pas_2', 'pas_11', 'pas_central2'],
  },
  pas_11: {
    id: 'pas_11',
    piso: 'Piso1',
    x: 1150,
    y: 540,
    tipo: 'pasillo',
    conexiones: ['pas_central1', 'esc_ed1centr', 'ofi_100'],
  },
  ofi_100: {
    id: '40001',
    piso: 'Piso1',
    x: 1020,
    y: 540,
    nombres: ['ciencias exactas 1'],
    tipo: 'oficina',
    conexiones: ['pas_11', 'ofi_101'],
  },
  ofi_101: {
    id: '40002',
    piso: 'Piso1',
    x: 850,
    y: 540,
    nombres: ['prefectura'],
    tipo: 'oficina',
    conexiones: ['ofi_100', 'salon_101'],
  },
  salon_101: {
    id: '101',
    piso: 'Piso1',
    x: 760,
    y: 540,
    nombres: ['salon 101'],
    tipo: 'salon',
    conexiones: ['ofi_101', 'salon_102'],
  },
  salon_102: {
    id: '102',
    piso: 'Piso1',
    x: 675,
    y: 540,
    nombres: ['salon 102'],
    tipo: 'salon',
    conexiones: ['salon_101', 'salon_103'],
  },
  salon_103: {
    id: '103',
    piso: 'Piso1',
    x: 585,
    y: 540,
    nombres: ['salon 103'],
    tipo: 'salon',
    conexiones: ['salon_102', 'salon_104'],
  },
  salon_104: {
    id: '104',
    piso: 'Piso1',
    x: 510,
    y: 540,
    nombres: ['salon 104'],
    tipo: 'salon',
    conexiones: ['salon_103', 'salon_105'],
  },
  salon_105: {
    id: '105',
    piso: 'Piso1',
    x: 415,
    y: 540,
    nombres: ['salon 105'],
    tipo: 'salon',
    conexiones: ['salon_104', 'pas_ed1ed5'],
  },
  pas_ed1ed5: {
    id: 'pas_ed1ed5',
    piso: 'Piso1',
    x: 290,
    y: 540,
    tipo: 'pasillo',
    conexiones: ['salon_105', 'esc_ed1ed5', 'pas_51', 'pas_cap1'],
  },

  // ==== EDIFICIO 2 - PISO 1 ====
  pas_central2: {
    id: 'pas_central2',
    piso: 'Piso1',
    x: 1225,
    y: 820,
    tipo: 'pasillo',
    conexiones: ['pas_central1', 'pas_centrbib', 'pas_21'],
  },
  pas_21: {
    id: 'pas_21',
    piso: 'Piso1',
    x: 1150,
    y: 820,
    tipo: 'pasillo',
    conexiones: ['pas_central2', 'esc_ed2centr', 'ofi_201'],
  },
  ofi_201: {
    id: '40004',
    piso: 'Piso1',
    x: 1070,
    y: 820,
    nombres: ['enfermeria', 'consultorio medico'],
    tipo: 'oficina',
    conexiones: ['pas_21', 'ofi_202'],
  },
  ofi_202: {
    id: '40003',
    piso: 'Piso1',
    x: 960,
    y: 820,
    nombres: ['ciencias exactas 2'],
    tipo: 'oficina',
    conexiones: ['ofi_201', 'salon_203'],
  },
  salon_203: {
    id: '203',
    piso: 'Piso1',
    x: 845,
    y: 820,
    nombres: ['salon 203'],
    tipo: 'salon',
    conexiones: ['ofi_202', 'salon_204'],
  },
  salon_204: {
    id: '204',
    piso: 'Piso1',
    x: 755,
    y: 820,
    nombres: ['salon 204'],
    tipo: 'salon',
    conexiones: ['salon_203', 'salon_205'],
  },
  salon_205: {
    id: '205',
    piso: 'Piso1',
    x: 670,
    y: 820,
    nombres: ['salon 205'],
    tipo: 'salon',
    conexiones: ['salon_204', 'salon_206'],
  },
  salon_206: {
    id: '206',
    piso: 'Piso1',
    x: 590,
    y: 820,
    nombres: ['salon 206'],
    tipo: 'salon',
    conexiones: ['salon_205', 'salon_207'],
  },
  salon_207: {
    id: '207',
    piso: 'Piso1',
    x: 540,
    y: 820,
    nombres: ['salon 207'],
    tipo: 'salon',
    conexiones: ['salon_208', 'salon_206'],
  },
  salon_208: {
    id: '208',
    piso: 'Piso1',
    x: 489,
    y: 820,
    nombres: ['salon 208'],
    tipo: 'salon',
    conexiones: ['salon_207', 'salon_209'],
  },
  salon_209: {
    id: '209',
    piso: 'Piso1',
    x: 400,
    y: 820,
    nombres: ['salon 209'],
    tipo: 'salon',
    conexiones: ['baño_m2', 'salon_208'],
  },
  baño_m2: {
    id: 'baño_m2',
    piso: 'Piso1',
    x: 285,
    y: 820,
    tipo: 'baño_m',
    conexiones: ['pas_52', 'salon_209'],
  },

  // ==== EDIFICIO 3 - PISO 1 ====
  snacks_jardis: {
    id: 'snacks_jardis',
    piso: 'Piso1',
    x: 1380,
    y: 925,
    tipo: 'pasillo',
    conexiones: ['jardis', 'pas_centrbib'],
  },
  pas_centrbib: {
    id: 'pas_centrbib',
    piso: 'Piso1',
    x: 1225,
    y: 925,
    tipo: 'pasillo',
    conexiones: ['snacks_jardis', 'pas_central2', 'pas_central3'],
  },
  pas_central3: {
    id: 'pas_centr3',
    piso: 'Piso1',
    x: 1225,
    y: 1060,
    tipo: 'pasillo',
    conexiones: ['pas_centrbib', 'pas_centrcafe', 'pas_31'],
  },
  pas_31: {
    id: 'pas_31',
    piso: 'Piso1',
    x: 1150,
    y: 1060,
    tipo: 'pasillo',
    conexiones: ['pas_central3', 'esc_ed3', 'ofi_301'],
  },
  ofi_301: {
    id: '40011',
    piso: 'Piso1',
    x: 1050,
    y: 1060,
    nombres: ['pastoral'],
    tipo: 'oficina',
    conexiones: ['pas_31', 'salon_301'],
  },
  salon_301: {
    id: '301',
    piso: 'Piso1',
    x: 910,
    y: 1060,
    nombres: ['salon 301'],
    tipo: 'salon',
    conexiones: ['ofi_301', 'salon_303'],
  },
  salon_303: {
    id: '303',
    piso: 'Piso1',
    x: 810,
    y: 1060,
    nombres: ['salon 303'],
    tipo: 'salon',
    conexiones: ['salon_301', 'pas_32'],
  },
  pas_32: {
    id: 'pas_32',
    piso: 'Piso1',
    x: 710,
    y: 1060,
    tipo: 'pasillo',
    conexiones: ['salon_303', 'pas_33', 'salon_304'],
  },
  salon_304: {
    id: '304',
    piso: 'Piso1',
    x: 670,
    y: 1060,
    nombres: ['salon 304'],
    tipo: 'salon',
    conexiones: ['pas_32', 'salon_305'],
  },
  salon_305: {
    id: '305',
    piso: 'Piso1',
    x: 605,
    y: 1060,
    nombres: ['salon 305'],
    tipo: 'pasillo',
    conexiones: ['salon_304'],
  },
  pas_33: {
    id: 'pas_33',
    piso: 'Piso1',
    x: 710,
    y: 995,
    tipo: 'pasillo',
    conexiones: ['pas_32', 'pas_34'],
  },
  pas_34: {
    id: 'pas_34',
    piso: 'Piso1',
    x: 550,
    y: 995,
    tipo: 'pasillo',
    conexiones: ['pas_33', 'pas_35'],
  },
  pas_35: {
    id: 'pas_35',
    piso: 'Piso1',
    x: 520,
    y: 935,
    tipo: 'pasillo',
    conexiones: ['pas_34', 'pas_53'],
  },

  // ==== EDIFICIO 4 - PISO 1 ====
  salon_401: {
    id: '401',
    piso: 'Piso1',
    x: 940,
    y: 1290,
    nombres: ['salon 401'],
    tipo: 'salon',
    conexiones: ['subway', 'salon_402'],
  },
  salon_402: {
    id: '402',
    piso: 'Piso1',
    x: 840,
    y: 1290,
    nombres: ['salon 402'],
    tipo: 'salon',
    conexiones: ['salon_401', 'salon_403'],
  },
  salon_403: {
    id: '403',
    piso: 'Piso1',
    x: 720,
    y: 1290,
    nombres: ['salon 403'],
    tipo: 'salon',
    conexiones: ['salon_402', 'ofi_401'],
  },
  ofi_401: {
    id: '40010',
    piso: 'Piso1',
    x: 590,
    y: 1290,
    nombres: ['division de preparatoria'],
    tipo: 'oficina',
    conexiones: ['salon_403', 'pas_41'],
  },
  pas_41: {
    id: 'pas_41',
    piso: 'Piso1',
    x: 510,
    y: 1290,
    tipo: 'pasillo',
    conexiones: ['ofi_401', 'pas_gastro2', 'ofi_402'],
  },
  ofi_402: {
    id: '40009',
    piso: 'Piso1',
    x: 450,
    y: 1290,
    nombres: ['orientacion academica'],
    tipo: 'oficina',
    conexiones: ['pas_41', 'pas_42'],
  },
  pas_gastro2: {
    id: 'pas_gastro2',
    piso: 'Piso1',
    x: 510,
    y: 1190,
    tipo: 'pasillo',
    conexiones: ['pas_41', 'ele_gastro1'],
  },
  pas_42: {
    id: 'pas_42',
    piso: 'Piso1',
    x: 295,
    y: 1290,
    tipo: 'pasillo',
    conexiones: ['pas_54', 'ofi_402', 'esc_ed4'],
  },

  // ==== EDIFICIO 5 - PISO 1 ====
  pas_51: {
    id: 'pas_51',
    piso: 'Piso1',
    x: 240,
    y: 545,
    tipo: 'pasillo',
    conexiones: ['pas_ed1ed5', 'ele500', 'salon_501', 'salon_502'],
  },
  salon_501: {
    id: '501',
    piso: 'Piso1',
    x: 240,
    y: 475,
    nombres: ['salon 501'],
    tipo: 'pasillo',
    conexiones: ['pas_51'],
  },
  salon_502: {
    id: '502',
    piso: 'Piso1',
    x: 240,
    y: 615,
    nombres: ['salon 502'],
    tipo: 'salon',
    conexiones: ['pas_51', 'salon_503'],
  },
  salon_503: {
    id: '503',
    piso: 'Piso1',
    x: 240,
    y: 730,
    nombres: ['salon 503'],
    tipo: 'salon',
    conexiones: ['salon_502', 'pas_52'],
  },
  pas_52: {
    id: 'pas_52',
    piso: 'Piso1',
    x: 240,
    y: 815,
    tipo: 'pasillo',
    conexiones: ['baño_m2', 'salon_503', 'salon_504'],
  },
  salon_504: {
    id: '504',
    piso: 'Piso1',
    x: 240,
    y: 865,
    nombres: ['salon 504'],
    tipo: 'salon',
    conexiones: ['pas_52', 'pas_53'],
  },
  pas_53: {
    id: 'pas_53',
    piso: 'Piso1',
    x: 240,
    y: 935,
    tipo: 'pasillo',
    conexiones: ['pas_35', 'salon_504', 'pas_gastro1'],
  },
  salon_505: {
    id: '505',
    piso: 'Piso1',
    x: 240,
    y: 1130,
    nombres: ['salon 505'],
    tipo: 'salon',
    conexiones: ['pas_gastro1', 'baño_m5'],
  },
  baño_m5: {
    id: 'baño_m5',
    piso: 'Piso1',
    x: 240,
    y: 1235,
    tipo: 'baño_m',
    conexiones: ['salon_505', 'pas_54'],
  },
  baño_h5: {
    id: 'baño_h5',
    piso: 'Piso1',
    x: 240,
    y: 1315,
    tipo: 'baño_h',
    conexiones: ['salon_506', 'pas_54'],
  },
  pas_54: {
    id: 'pas_54',
    piso: 'Piso1',
    x: 240,
    y: 1290,
    tipo: 'pasillo',
    conexiones: ['pas_42', 'baño_m5', 'baño_h5'],
  },
  salon_506: {
    id: '506',
    piso: 'Piso1',
    x: 240,
    y: 1395,
    nombres: ['salon 506'],
    tipo: 'salon',
    conexiones: ['baño_h5', 'pas_55', 'pas_55'],
  },
  baño_5: {
    id: 'baño_5',
    piso: 'Piso1',
    x: 240,
    y: 1440,
    tipo: 'baño',
    conexiones: ['pas_55'],
  },
  pas_55: {
    id: 'pas_55',
    piso: 'Piso1',
    x: 240,
    y: 1420,
    tipo: 'pasillo',
    conexiones: ['salon_506', 'baño_5', 'pas_lab4'],
  },

  // ==== LABORATORIOS Y EXTERIORES - PISO 1 ====
  ent_porton: {
    id: 'ent_porton',
    piso: 'Piso1',
    x: 15,
    y: 1530,
    tipo: 'entrada',
    nombres: ['porton', 'rola'],
    conexiones: ['pas_lab41'],
  },
  pas_lab41: {
    id: 'pas_lab41',
    piso: 'Piso1',
    x: 330,
    y: 1530,
    tipo: 'pasillo',
    conexiones: ['ent_porton', 'pas_lab42'],
  },
  pas_lab42: {
    id: 'pas_lab42',
    piso: 'Piso1',
    x: 330,
    y: 1570,
    tipo: 'pasillo',
    conexiones: ['pas_lab41', 'esc_lab4', 'pas_lab4'],
  },
  pas_lab4: {
    id: 'pas_lab4',
    piso: 'Piso1',
    x: 330,
    y: 1460,
    tipo: 'pasillo',
    conexiones: ['pas_55', 'pas_lab42', 'salon_432'],
  },
  salon_432: {
    id: '432',
    piso: 'Piso1',
    x: 450,
    y: 1460,
    nombres: ['salon 432', 'laboratorio mecanica aplicada'],
    tipo: 'salon',
    conexiones: ['pas_lab4', 'salon_431'],
  },
  salon_431: {
    id: '431',
    piso: 'Piso1',
    x: 710,
    y: 1460,
    nombres: ['salon 432', 'laboratorio de quimica'],
    tipo: 'salon',
    conexiones: ['salon_432', 'pas_lab43'],
  },
  pas_lab43: {
    id: 'pas_lab43',
    piso: 'Piso1',
    x: 870,
    y: 1460,
    tipo: 'pasillo',
    conexiones: ['salon_431', 'pergola', 'pas_lab44'],
  },
  pas_lab44: {
    id: 'pas_lab44',
    piso: 'Piso1',
    x: 870,
    y: 1570,
    tipo: 'pasillo',
    conexiones: ['esc_lab4', 'pas_lab43', 'pas_afuera3'],
  },
  pas_afuera3: {
    id: 'NODO_ID',
    piso: 'Piso1',
    x: 1115,
    y: 1570,
    tipo: 'pasillo',
    nombres: [''],
    conexiones: ['pas_lab44', 'pas_afuera2', 'pas_afuera1'],
  },
  pergola: {
    id: 'pergola',
    piso: 'Piso1',
    x: 1000,
    y: 1460,
    tipo: 'edificio',
    nombres: ['pergola'],
    conexiones: ['pas_lab43', 'pas_afuera2'],
  },
  pas_afuera2: {
    id: 'pas_afuera2',
    piso: 'Piso1',
    x: 1115,
    y: 1460,
    tipo: 'pasillo',
    nombres: [''],
    conexiones: ['pergola', 'pas_afuera3', 'pas_perg'],
  },
  pas_afuera1: {
    id: 'pas_afuera1',
    piso: 'Piso1',
    x: 1195,
    y: 1620,
    tipo: 'pasillo',
    conexiones: ['medicina', 'pas_afuera3', 'pas_afuera1'],
  },
  medicina: {
    id: 'medicina',
    piso: 'Piso1',
    x: 1195,
    y: 1960,
    tipo: 'edificio',
    nombres: ['medicina'],
    conexiones: ['pas_afuera1'],
  },

  // ==== CAFE Y SERVICIOS - PISO 1 ====
  snacks: {
    id: '90003',
    piso: 'Piso1',
    x: 1380,
    y: 1180,
    tipo: 'edificio',
    conexiones: ['pas_cafe', 'pas_subway', 'pas_centrcafe'],
  },
  pas_centrcafe: {
    id: 'snacks',
    piso: 'Piso1',
    x: 1215,
    y: 1175,
    tipo: 'pasillo',
    conexiones: ['pas_central3', 'pas_cafe', 'pas_subway', 'snacks', 'pas_perg'],
  },
  pas_cafe: {
    id: 'pas_cafe',
    piso: 'Piso1',
    x: 1290,
    y: 1315,
    tipo: 'pasillo',
    conexiones: ['snacks', 'cafe', 'sorbitos', 'pas_perg', 'pas_subway', 'pas_centrcafe'],
  },
  cafe: {
    id: '90002',
    piso: 'Piso1',
    x: 1305,
    y: 1420,
    tipo: 'edificio',
    nombres: ['cafe', 'cafeteria'],
    conexiones: ['sorbitos', 'pas_cafe', 'pas_subway'],
  },
  sorbitos: {
    id: '90004',
    piso: 'Piso1',
    x: 1150,
    y: 1405,
    tipo: 'edificio',
    nombres: ['sorbitos'],
    conexiones: ['cafe', 'pas_cafe', 'pas_subway', 'pas_perg'],
  },
  pas_perg: {
    id: 'pas_perg',
    piso: 'Piso1',
    x: 1115,
    y: 1405,
    tipo: 'pasillo',
    conexiones: ['pas_subway', 'sorbitos', 'pas_afuera2', 'pas_cafe', 'pas_centrcafe'],
  },
  pas_subway: {
    id: 'pas_subway',
    piso: 'Piso1',
    x: 1115,
    y: 1290,
    tipo: 'pasillo',
    conexiones: ['subway', 'pas_perg', 'sorbitos', 'pas_cafe', 'pas_centrcafe', 'snacks', 'cafe'],
  },
  subway: {
    id: '90005',
    piso: 'Piso1',
    x: 1090,
    y: 1290,
    tipo: 'edificio',
    nombres: ['subway'],
    conexiones: ['pas_subway', 'salon_401'],
  },

  // ==== EDIFICIOS ESPECIALES - PISO 1 ====
  pas_cap1: {
    id: 'pas_cap1',
    piso: 'Piso1',
    x: 290,
    y: 310,
    tipo: 'pasillo',
    conexiones: ['pas_ed1ed5', 'pas_cap2'],
  },
  pas_cap2: {
    id: 'pas_cap2',
    piso: 'Piso1',
    x: 84,
    y: 310,
    tipo: 'pasillo',
    conexiones: ['pas_cap1', 'capilla'],
  },
  capilla: {
    id: '90000',
    piso: 'Piso1',
    x: 75,
    y: 230,
    tipo: 'edificio',
    nombres: ['capilla'],
    conexiones: ['pas_cap2'],
  },
  pas_est2: {
    id: 'pas_est2',
    piso: 'Piso1',
    x: 1975,
    y: 920,
    tipo: 'pasillo',
    conexiones: ['pas_est1', 'jardis'],
  },
  jardis: {
    id: 'jardis',
    piso: 'Piso1',
    x: 1685,
    y: 925,
    tipo: 'edificio',
    nombres: ['jardineras', 'jardis'],
    conexiones: ['pas_est2', 'biblio', 'snacks_jardis'],
  },
  biblio: {
    id: '90001',
    piso: 'Piso1',
    x: 1685,
    y: 1170,
    tipo: 'edificio',
    nombres: ['biblio', 'biblioteca', 'centro de informacion'],
    conexiones: ['jardis'],
  },
  pas_gastro1: {
    id: 'pas_gastro1',
    piso: 'Piso1',
    x: 240,
    y: 1095,
    tipo: 'pasillo',
    conexiones: ['pas_53', 'gastro', 'salon_505'],
  },
  gastro: {
    id: '901',
    piso: 'Piso1',
    x: 300,
    y: 1095,
    tipo: 'edificio',
    nombres: ['gastro', 'gastronomia'],
    conexiones: ['pas_gastro1'],
  },

  // ==== PISO 2 - ESCALERAS ====
  p2_esc_central: {
    id: 'p2_esc_central',
    piso: 'Piso2',
    x: 1110,
    y: 320,
    tipo: 'escalera',
    conexiones: ['p2_pas_3', 'esc_central'],
  },
  p2_esc_ed6: {
    id: 'p2_esc_ed6',
    piso: 'Piso2',
    x: 1860,
    y: 320,
    tipo: 'escalera',
    conexiones: ['p2_pas_4', 'esc_ed6'],
  },
  p2_esc_ed1centr: {
    id: 'p2_esc_ed1centr',
    piso: 'Piso2',
    x: 1150,
    y: 600,
    tipo: 'escalera',
    conexiones: ['p2_pas_11', 'esc_ed1centr'],
  },
  p2_esc_ed1ed5: {
    id: 'p2_esc_ed1ed5',
    piso: 'Piso2',
    x: 290,
    y: 600,
    tipo: 'escalera',
    conexiones: ['p2_pas_ed1ed5', 'esc_ed1ed5'],
  },
  p2_esc_ed2centr: {
    id: 'p2_esc_ed2centr',
    piso: 'Piso2',
    x: 1150,
    y: 870,
    tipo: 'escalera',
    conexiones: ['p2_pas_21', 'esc_ed2centr'],
  },
  p2_esc_ed3: {
    id: 'p2_esc_ed3',
    piso: 'Piso2',
    x: 1150,
    y: 1110,
    tipo: 'escalera',
    conexiones: ['p2_pas_31', 'esc_ed3'],
  },
  p2_ele_gastro1: {
    id: 'p2_ele_gastro1',
    piso: 'Piso2',
    x: 560,
    y: 1190,
    tipo: 'escalera',
    conexiones: ['p2_pas_gastro2', 'ele_gastro1'],
  },
  p2_esc_ed4: {
    id: 'p2_esc_ed4',
    piso: 'Piso2',
    x: 295,
    y: 1360,
    tipo: 'escalera',
    conexiones: ['p2_pas_42', 'esc_ed4'],
  },
  p2_ele500: {
    id: 'p2_ele500',
    piso: 'Piso2',
    x: 200,
    y: 550,
    tipo: 'escalera',
    conexiones: ['p2_pas_51', 'ele500'],
  },
  p2_esc_lab4: {
    id: 'p2_esc_lab4',
    piso: 'Piso2',
    x: 580,
    y: 1570,
    tipo: 'escalera',
    conexiones: ['esc_lab4', 'salon_433'],
  },

  // ==== EDIFICIO 6 - PISO 2 ====
  p2_pas_2: {
    id: 'p2_pas_2',
    piso: 'Piso2',
    x: 1200,
    y: 300,
    tipo: 'pasillo',
    conexiones: ['p2_pas_3', 'ofi_611', 'ofi_612', 'p2_central1'],
  },
  p2_pas_3: {
    id: 'p2_pas_3',
    piso: 'Piso2',
    x: 1110,
    y: 300,
    tipo: 'pasillo',
    conexiones: ['p2_pas_2', 'p2_esc_central'],
  },
  ofi_611: {
    id: '50001',
    piso: 'Piso2',
    x: 1090,
    y: 300,
    nombres: ['comunicacion institucional', 'becas y admisiones', 'sorteo anahuac'],
    tipo: 'oficina',
    conexiones: ['p2_pas_2'],
  },
  ofi_612: {
    id: '50002',
    piso: 'Piso2',
    x: 1470,
    y: 300,
    nombres: ['capital humano', 'defensoria', 'administrativo', 'contraloria'],
    tipo: 'oficina',
    conexiones: ['p2_pas_2', 'ofi_613'],
  },
  ofi_613: {
    id: '50003',
    piso: 'Piso2',
    x: 1740,
    y: 300,
    nombres: ['compromiso social', 'auditoria'],
    tipo: 'oficina',
    conexiones: ['ofi_612', 'p2_pas_4'],
  },
  p2_pas_4: {
    id: 'p2_pas_4',
    piso: 'Piso2',
    x: 1860,
    y: 300,
    tipo: 'pasillo',
    conexiones: ['p2_esc_ed6', 'ofi_613'],
  },

  // ==== EDIFICIO 1 - PISO 2 ====
  p2_pas_11: {
    id: 'p2_pas_11',
    piso: 'Piso2',
    x: 1150,
    y: 540,
    tipo: 'pasillo',
    conexiones: ['p2_esc_ed1centr', 'p2_central1', 'salon_106'],
  },
  p2_pas_ed1ed5: {
    id: 'p2_pas_ed1ed5',
    piso: 'Piso2',
    x: 290,
    y: 540,
    tipo: 'pasillo',
    conexiones: ['p2_esc_ed1ed5', 'p2_pas_51', 'salon_116'],
  },
  salon_106: {
    id: '106',
    piso: 'Piso2',
    x: 1100,
    y: 540,
    nombres: ['sala de juicios orales', 'salon 106'],
    tipo: 'salon',
    conexiones: ['p2_pas_11', 'salon_107'],
  },
  salon_107: {
    id: '107',
    piso: 'Piso2',
    x: 985,
    y: 540,
    nombres: ['salon 107'],
    tipo: 'salon',
    conexiones: ['salon_106', 'salon_108'],
  },
  salon_108: {
    id: '108',
    piso: 'Piso2',
    x: 870,
    y: 540,
    nombres: ['salon 108'],
    tipo: 'salon',
    conexiones: ['salon_107', 'salon_109'],
  },
  salon_109: {
    id: '109',
    piso: 'Piso2',
    x: 760,
    y: 540,
    nombres: ['salon 109'],
    tipo: 'salon',
    conexiones: ['salon_108', 'salon_110'],
  },
  salon_110: {
    id: '110',
    piso: 'Piso2',
    x: 640,
    y: 540,
    nombres: ['salon 110'],
    tipo: 'salon',
    conexiones: ['salon_109', 'salon_111'],
  },
  salon_111: {
    id: '111',
    piso: 'Piso2',
    x: 530,
    y: 540,
    nombres: ['salon 111'],
    tipo: 'salon',
    conexiones: ['salon_110', 'salon_116'],
  },
  salon_116: {
    id: '116',
    piso: 'Piso2',
    x: 405,
    y: 540,
    nombres: ['salon 116', 'laboratorio de diseño digital'],
    tipo: 'salon',
    conexiones: ['salon_111', 'p2_pas_ed1ed5'],
  },

  // ==== EDIFICIO 2 - PISO 2 ====
  p2_pas_21: {
    id: 'p2_pas_21',
    piso: 'Piso2',
    x: 1150,
    y: 820,
    tipo: 'pasillo',
    conexiones: ['p2_esc_ed2centr', 'p2_central2', 'salon_210'],
  },
  salon_210: {
    id: '210',
    piso: 'Piso2',
    x: 1105,
    y: 820,
    nombres: ['salon 210'],
    tipo: 'salon',
    conexiones: ['p2_pas_21', 'salon_211'],
  },
  salon_211: {
    id: '211',
    piso: 'Piso2',
    x: 1025,
    y: 820,
    nombres: ['salon 211'],
    tipo: 'salon',
    conexiones: ['salon_210', 'salon_212'],
  },
  salon_212: {
    id: '212',
    piso: 'Piso2',
    x: 944,
    y: 820,
    nombres: ['salon 212'],
    tipo: 'salon',
    conexiones: ['salon_211', 'salon_213'],
  },
  salon_213: {
    id: '213',
    piso: 'Piso2',
    x: 850,
    y: 820,
    nombres: ['salon 213'],
    tipo: 'salon',
    conexiones: ['salon_212', 'salon_214'],
  },
  salon_214: {
    id: '214',
    piso: 'Piso2',
    x: 760,
    y: 820,
    nombres: ['salon 214'],
    tipo: 'salon',
    conexiones: ['salon_213', 'salon_215'],
  },
  salon_215: {
    id: '215',
    piso: 'Piso2',
    x: 680,
    y: 820,
    nombres: ['salon 215'],
    tipo: 'salon',
    conexiones: ['salon_214', 'salon_216'],
  },
  salon_216: {
    id: '216',
    piso: 'Piso2',
    x: 595,
    y: 820,
    nombres: ['salon 216'],
    tipo: 'salon',
    conexiones: ['salon_215', 'salon_217'],
  },
  salon_217: {
    id: '217',
    piso: 'Piso2',
    x: 535,
    y: 820,
    nombres: ['salon 217'],
    tipo: 'salon',
    conexiones: ['salon_216', 'salon_218'],
  },
  salon_218: {
    id: '218',
    piso: 'Piso2',
    x: 480,
    y: 820,
    nombres: ['salon 218'],
    tipo: 'salon',
    conexiones: ['salon_217', 'salon_219'],
  },
  salon_219: {
    id: '219',
    piso: 'Piso2',
    x: 400,
    y: 820,
    nombres: ['salon 219'],
    tipo: 'salon',
    conexiones: ['salon_218', 'baño_h2arriba'],
  },
  baño_h2arriba: {
    id: 'baño_h2arriba',
    piso: 'Piso2',
    x: 285,
    y: 820,
    tipo: 'baño_h',
    conexiones: ['salon_219', 'p2_pas_52'],
  },

  // ==== EDIFICIO 3 - PISO 2 ====
  p2_pas_31: {
    id: 'p2_pas_31',
    piso: 'Piso2',
    x: 1150,
    y: 1060,
    tipo: 'pasillo',
    conexiones: ['p2_esc_ed3', 'baño_m3arriba', 'baño_h3arriba', 'p2_centralb', 'salon_306'],
  },
  salon_306: {
    id: '306',
    piso: 'Piso2',
    x: 1100,
    y: 1060,
    nombres: ['salon_306'],
    tipo: 'pasillo',
    conexiones: ['p2_pas_31', 'salon_307'],
  },
  salon_307: {
    id: '307',
    piso: 'Piso2',
    x: 1000,
    y: 1060,
    nombres: ['salon_307'],
    tipo: 'pasillo',
    conexiones: ['salon_306', 'salon_308'],
  },
  salon_308: {
    id: '308',
    piso: 'Piso2',
    x: 890,
    y: 1060,
    nombres: ['salon_308'],
    tipo: 'pasillo',
    conexiones: ['salon_307', 'salon_309'],
  },
  salon_309: {
    id: '309',
    piso: 'Piso2',
    x: 790,
    y: 1060,
    nombres: ['salon_309'],
    tipo: 'pasillo',
    conexiones: ['salon_308', 'salon_310'],
  },
  salon_310: {
    id: '310',
    piso: 'Piso2',
    x: 685,
    y: 1060,
    nombres: ['salon_310'],
    tipo: 'pasillo',
    conexiones: ['salon_309', 'salon_311'],
  },
  salon_311: {
    id: '311',
    piso: 'Piso2',
    x: 605,
    y: 1060,
    nombres: ['Taller de diseño grafico', 'salon_311'],
    tipo: 'pasillo',
    conexiones: ['salon_310'],
  },

  // ==== EDIFICIO 4 - PISO 2 ====
  p2_pas_gastro2: {
    id: 'p2_pas_gastro2',
    piso: 'Piso2',
    x: 510,
    y: 1190,
    tipo: 'pasillo',
    conexiones: ['p2_ele_gastro1'],
  },
  p2_pas_42: {
    id: 'p2_pas_42',
    piso: 'Piso2',
    x: 295,
    y: 1290,
    tipo: 'pasillo',
    conexiones: ['p2_pas_54', 'p2_esc_ed4', 'salon_411'],
  },
  salon_411: {
    id: '411',
    piso: 'Piso2',
    x: 380,
    y: 1290,
    nombres: ['salon 411'],
    tipo: 'salon',
    conexiones: ['p2_pas_42', 'salon_410'],
  },
  salon_410: {
    id: '410',
    piso: 'Piso2',
    x: 465,
    y: 1290,
    nombres: ['salon 410'],
    tipo: 'salon',
    conexiones: ['salon_411', 'salon_409'],
  },
  salon_409: {
    id: '409',
    piso: 'Piso2',
    x: 620,
    y: 1290,
    nombres: ['aula activa 409', 'salon 409'],
    tipo: 'salon',
    conexiones: ['salon_410', 'salon_408'],
  },
  salon_408: {
    id: '408',
    piso: 'Piso2',
    x: 695,
    y: 1290,
    nombres: ['salon 408'],
    tipo: 'salon',
    conexiones: ['salon_409', 'salon_407'],
  },
  salon_407: {
    id: '407',
    piso: 'Piso2',
    x: 840,
    y: 1290,
    nombres: ['laboratorio de electronica analogica', 'salon 407', 'laboratorio 407'],
    tipo: 'salon',
    conexiones: ['salon_408', 'salon_406'],
  },
  salon_406: {
    id: '406',
    piso: 'Piso2',
    x: 885,
    y: 1290,
    nombres: ['laboratorio de electronica digital', 'salon 406', 'laboratorio 406'],
    tipo: 'salon',
    conexiones: ['salon_407'],
  },

  // ==== EDIFICIO 5 - PISO 2 ====
  p2_pas_51: {
    id: 'p2_pas_51',
    piso: 'Piso2',
    x: 240,
    y: 545,
    tipo: 'pasillo',
    conexiones: ['p2_pas_ed1ed5', 'p2_ele500', 'ofi_511', 'ofi_512'],
  },
  p2_pas_52: {
    id: 'p2_pas_52',
    piso: 'Piso2',
    x: 240,
    y: 815,
    tipo: 'pasillo',
    conexiones: ['salon_512', 'ofi_512', 'baño_h2arriba'],
  },
  p2_pas_54: {
    id: 'p2_pas_54',
    piso: 'Piso2',
    x: 240,
    y: 1290,
    tipo: 'pasillo',
    conexiones: ['p2_pas_42', 'salon_516', 'ofi_514'],
  },
  ofi_511: {
    id: '50008',
    piso: 'Piso2',
    x: 240,
    y: 455,
    nombres: ['desarrollo academico'],
    tipo: 'oficina',
    conexiones: ['p2_pas_51'],
  },
  ofi_512: {
    id: '50007',
    piso: 'Piso2',
    x: 240,
    y: 730,
    nombres: ['division de humanidades'],
    tipo: 'oficina',
    conexiones: ['p2_pas_51', 'p2_pas_52'],
  },
  salon_512: {
    id: '512',
    piso: 'Piso2',
    x: 240,
    y: 890,
    nombres: ['aula activa 512', 'salon 512'],
    tipo: 'salon',
    conexiones: ['p2_pas_52', 'caadi'],
  },
  caadi: {
    id: '50006',
    piso: 'Piso2',
    x: 240,
    y: 1160,
    nombres: ['caadi', 'centro de idiomas'],
    tipo: 'oficina',
    conexiones: ['salon_512', 'ofi_514'],
  },
  ofi_514: {
    id: '50009',
    piso: 'Piso2',
    x: 240,
    y: 1240,
    nombres: ['direccion de preparatoria'],
    tipo: 'oficina',
    conexiones: ['p2_pas_54', 'caadi'],
  },
  salon_516: {
    id: '516',
    piso: 'Piso2',
    x: 240,
    y: 1365,
    nombres: ['aula activa 516', 'salon 516'],
    tipo: 'salon',
    conexiones: ['baño_5arriba', 'p2_pas_54'],
  },
  baño_5arriba: {
    id: 'baño_5arriba',
    piso: 'Piso2',
    x: 240,
    y: 1435,
    tipo: 'baño',
    conexiones: ['salon_516'],
  },

  // ==== LAB Y EXTERIORES - PISO 2 ====
  salon_433: {
    id: '433',
    piso: 'Piso2',
    x: 790,
    y: 1570,
    tipo: 'pasillo',
    nombres: ['laboratorio de robotica', 'salon 433'],
    conexiones: ['p2_esc_lab4'],
  },

  // ==== PASILLOS CENTRALES - PISO 2 ====
  p2_central1: {
    id: 'p2_central1',
    piso: 'Piso2',
    x: 1200,
    y: 500,
    tipo: 'pasillo',
    conexiones: ['baño_h1arriba', 'p2_pas_2', 'p2_pas_11'],
  },
  baño_h1arriba: {
    id: 'baño_h1arriba',
    piso: 'Piso2',
    x: 1200,
    y: 560,
    tipo: 'baño_h',
    conexiones: ['p2_central2', 'p2_central1'],
  },
  p2_central2: {
    id: 'p2_central2',
    piso: 'Piso2',
    x: 1200,
    y: 820,
    tipo: 'pasillo',
    conexiones: ['baño_m2arriba', 'baño_h1arriba', 'p2_pas_21'],
  },
  baño_m2arriba: {
    id: 'baño_m2arriba',
    piso: 'Piso2',
    x: 1200,
    y: 850,
    tipo: 'baño_m',
    conexiones: ['p2_central3', 'p2_central2'],
  },
  p2_central3: {
    id: 'p2_central3',
    piso: 'Piso2',
    x: 1200,
    y: 1025,
    tipo: 'pasillo',
    conexiones: ['p2_centralb', 'baño_m2arriba'],
  },
  p2_centralb: {
    id: 'p2_centralb',
    piso: 'Piso2',
    x: 1180,
    y: 1057,
    tipo: 'pasillo',
    conexiones: ['baño_h3arriba', 'baño_m3arriba', 'p2_central3', 'p2_pas_31'],
  },
  baño_h3arriba: {
    id: 'baño_h3arriba',
    piso: 'Piso2',
    x: 1185,
    y: 1074,
    tipo: 'baño_h',
    conexiones: ['p2_pas_31', 'p2_centralb'],
  },
  baño_m3arriba: {
    id: 'baño_m3arriba',
    piso: 'Piso2',
    x: 1185,
    y: 1097,
    tipo: 'baño_m',
    conexiones: ['p2_pas_31', 'p2_centralb'],
  },
}

// obtiene el archivo SVG para un piso especifico
// piso 1 -> piso1.svg, piso 2 -> piso2.svg
export function getFloorImage(floor: 1 | 2): string {
  return floor === 1 ? '/assets/maps/piso1.svg' : '/assets/maps/piso2.svg'
}

// obtiene el piso de un nodo por su ID
export function getFloorByNodeId(nodeId: string): 1 | 2 | null {
  const node = nodos[nodeId]
  if (!node) return null
  return node.piso === 'Piso1' ? 1 : 2
}

// busca un nodo por nombre (búsqueda flexible)
export function buscarNodoPorNombre(busqueda: string): string | undefined {
  const query = busqueda.toLowerCase().trim()
  if (!query) return undefined

  // primero intenta buscar por ID exacto
  if (nodos[query]) return query

  // luego por coincidencias en nombres alternativos
  return Object.keys(nodos).find((nodeKey) => {
    const nodo = nodos[nodeKey]
    const nombreEnArray =
      nodo.nombres && nodo.nombres.some((n) => n.toLowerCase().includes(query))
    const idCoincide = nodeKey.toLowerCase().includes(query)
    return nombreEnArray || idCoincide
  })
}

// retorna todos los nodos del grafo
export function getAllNodes(): MapGraph {
  return nodos
}
